export const GetWorldsFromStore = async () => {
    const worlds = [{
        code: 'en136',
        name: 'Oricos'
    }, {
        code: 'en135',
        name: 'Kepoi'
    }, {
        code: 'en134',
        name: 'Hyele'
    }, {
        code: 'en133',
        name: 'Elis'
    }, {
        code: 'en132',
        name: 'Doriscos'
    }, {
        code: 'en131',
        name: 'Chios'
    }, {
        code: 'en130',
        name: 'Bassae'
    }, {
        code: 'en129',
        name: 'Asine'
    }, {
        code: 'en128',
        name: 'Therma'
    }, {
        code: 'en122',
        name: 'Kelenderis'
    }, {
        code: 'en121',
        name: 'Himera'
    }, {
        code: 'en112',
        name: 'Naucratis'
    }, {
        code: 'en45',
        name: 'Hyperborea'
    }, {
        code: 'en41',
        name: 'Bellerophon'
    }, {
        code: 'en32',
        name: 'Achilles'
    }]
    return worlds
}